Algoritmo "crescente"

Var

   x, y : inteiro;

Inicio

      escreval("Digite dois numeros:")
      leia(x)
      leia(y)
      
      enquanto x<>y faca

               se x < y entao
                  escreval("ORDEM CRESCENTE!")
               senao
                    escreval("ORDEM DECRSCENTE!")
               fimse
               
      escreval("Digite outros dois numeros:")
      leia(x)
      leia(y)
      
      fimenquanto
      
      escreval("Numeros iguais!")


Fimalgoritmo